[package]
name = "cbm-program-activator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
sbf-entrypoint = []

[dependencies]
solana-program = { workspace = true }
